#lanuage
language: python
#version
python:
  - "3.9"

#env:
  #- NOSE_REDNOSE=1

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - pytest --cov=tests tests/

after_success:
  - coveralls

